### ISSUE TITLE
Express app settings methods need to be bound

### ISSUE THREAD

**Issue by eaceaser** [BuckleTypes/bs-express#19]
`app.get` and `app.set` aren't being bound currently. Since `get` is overloaded to be used for actual endpoint handler binding, we'd probably need to come up with alternative names. `getAppSetting` or `setAppSetting` maybe?

**Comment by bassjacob** [comment]
Hey @eaceaser, thanks for reporting. Do you have an example in JS that you'd like to support?

**Comment by glennsl** [comment]
Closing for lack of response. Reopen if needed.
