### ISSUE TITLE
Following the example `App.listen` won't work

### ISSUE THREAD

**Issue by mikeLspohn** [BuckleTypes/bs-express#20]
Anytime I try to use "App.listen" passing more than two arguments I get this (super!) error.

```
12 │ App.listen app port::3001 onListen::(fun e => Js.log e) ();

  This function has type Express.App.t => port::int => unit
  It only accepts 2 arguments; here, it's called with more.
  Maybe you forgot a semicolon?
```

This is the only way I have been able to get it to work so far.

`App.listen app port:3001;`

**Comment by bassjacob** [comment]
Hi @mikeLspohn,

How did you install bs-express? I haven't cut a release for a little while and the npm version is a little out of date.

**Comment by mikeLspohn** [comment]
Ahh, yeah I was using npm. What's the alternative? Just cloning repo? Thanks for the quick reply!

**Comment by mikeLspohn** [comment]
Ok, yeah that's all it was. Npm package is just out of date. Cloning the repo in it's current state this works fine 👍

**Comment by bassjacob** [comment]
For the record, if you want to use this from inside another package before I publish the next version, you can install it from github:

```bash
# for npm
npm i -S reasonml-community/bs-express
# or for yarn
yarn add reasonml-community/bs-express
```
