### ISSUE TITLE
Js.Json.reifyType removed

### ISSUE THREAD

**Issue by DrPandemic** [BuckleTypes/bs-express#22]
`Js.Json.reifyType` is used twice in [express.re](https://github.com/reasonml-community/bs-express/blob/master/src/express.re). It was a deprecated function with `bs-platform` 1.9.0, but with the current 1.9.3 this function was removed.

**Comment by cliedeman** [comment]
See https://github.com/reasonml-community/bs-express/pull/21

**Comment by DrPandemic** [comment]
Wow, that was a bad timing.

**Comment by bassjacob** [comment]
Thanks for reporting this 😄 I've released 0.0.4 which should fix this issue. Please let me know if there are any issues
