### ISSUE TITLE
Readme is a bit thin

### ISSUE THREAD

**Issue by glennsl** [BuckleTypes/bs-express#36]
bs-express is currently flagged as neglected [on redex](https://redex.github.io/package/bs-express/) because the readme is severely inadequate. And the quality of the bindings is really not deserving of such a poor readme.

I suggest adding, at the very least, a description of what it is including a link to express for more information, an overview of the state it's in, what's implemented and what's not, and a usage example.

\* nudge @ncthbrt \*

**Comment by ncthbrt** [comment]
@glennsl Definitely planning on adding some docs 😉
