### ISSUE TITLE
Websockets example

### ISSUE THREAD

**Issue by graforlock** [BuckleTypes/bs-express#49]
Can we add `bs-socket.io` to the example? 

It is unclear to me how to make them work together.

**Comment by ncthbrt** [comment]
How would you make them work together in JavaScript?

**Comment by graforlock** [comment]
One of the examples is here: https://github.com/reasonml-community/bs-socket.io/blob/master/example/ExampleServer.re

But relies on different, closer to original, express binding. Requires to define http binding as its not exported by default in neither `bs-node` nor `bs-express`.

**Comment by ncthbrt** [comment]
Will only get an opportunity to look at this next week @graforlock
