### ISSUE TITLE
es6 import issue

### ISSUE THREAD

**Issue by joprice** [BuckleTypes/bs-express#52]
When using bs-express with es6 modules,  I get the error:

`TypeError: Express is not a function`

If I create the following binding locally, I don't get the error:

`[@bs.module "express"] external express: unit => 'a = "default";`

It seems that express is set up to be used with a few different module patterns: https://github.com/expressjs/express/blob/431f65305eb78eba337356ec7637e4ee13d84195/lib/express.js#L28

I saw a similar change here https://github.com/apollographql/reason-apollo/pull/80/files and hit something suspiciously similar here https://github.com/rhysforyou/bs-enzyme/issues/14.

I'm a bit worried that changing this will break the commonjs usage. I don't know enough about the interop between all the different module specs.

**Comment by ncthbrt** [comment]
Would adding the below to `bsconfig.json` fix this issue
```  "package-specs": {
    "module": "commonjs",
    "in-source": true
  }```

**Comment by ncthbrt** [comment]
What happens if you're more specific about the module system used in bs-express?
```
"package-specs": {
    "module": "commonjs",
    "in-source": true
  },
```

**Comment by joprice** [comment]
Actually I just switched it and I get it with commonjs or es6.

**Comment by ncthbrt** [comment]
@joprice Is this still an issue?

**Comment by joprice** [comment]
Not sure. I ended up importing the file from js to get around it. If I get some free time soon I'll try it again.

**Comment by sync** [comment]
facing same issue with latest release and am using es6, also using latest bucklescript (v5)

**Comment by sync** [comment]
and yes this fixes it:
```
[@bs.module "express"] external express: unit => express = "default";

let app = express();
get(app, "*", (_, res) => send(res, "hi")) /* )*/ /*   */;

let default = app;
```
