### ISSUE TITLE
Adding CI and CD

### ISSUE THREAD

**Issue by ncthbrt** [BuckleTypes/bs-express#53]

**Comment by ncthbrt** [comment]
Still need to do this. Not developing in ReasonML recently so have been really procrastinating about setting up the tooling on my laptop. But a few nice changes have been building up and it'd be good to get it into npm

**Comment by ryb73** [comment]
Do you have an idea of what kind of changes you'd like implemented? It looks like there's already some sort of CD in place.

**Comment by ncthbrt** [comment]
There is some integration tests but they aren't being run on pull requests
as far as I know. Additionally, it would be nice to be able to make
releases without having to pull the repo and publish manually.

**Comment by ryb73** [comment]
I see. I wouldn't mind taking a look. I see [.travis.yml](https://github.com/reasonml-community/bs-express/blob/master/.travis.yml) already has some stuff related to deployment, is that not working?
