### ISSUE TITLE
Publish changes

### ISSUE THREAD

**Issue by ryb73** [BuckleTypes/bs-express#60]
There are a handful of changes that haven't been published yet. It'd be great if you could bump the version!

**Comment by ncthbrt** [comment]
Apologies. I'll make a release today.

**Comment by ncthbrt** [comment]
@ryb73 Released. I thought it was sorted, but turns out npm credentials had expired in CI process, I've now updated them

**Comment by ryb73** [comment]
Cool, thanks for the quick response!
