### ISSUE TITLE
0.11.0 published without lib/js

### ISSUE THREAD

**Issue by ryb73** [BuckleTypes/bs-express#61]
Sorry for continuing to bother you about this! I see that the npm published 0.11.0 is missing `lib/js`. Did you publish manually or through CI? If it was published by CI I can play around with it to see if there's a problem with my previous PR.

**Comment by ncthbrt** [comment]
It was through CI. It may be that you have to explicitly tell Travis to
retain artifacts between build and release.

**Comment by ncthbrt** [comment]
` skip_cleanup: true` seems to need to be added to deploy step

**Comment by ncthbrt** [comment]
Ah. So I made a release using skip cleanup, but I think an additional reason why lib is not included is because it `./lib` in `.gitignore`, which npm respects unless it is overridden by `.npmignore`

**Comment by ncthbrt** [comment]
On that note, is it best practise to include pre-compiled js files in libraries?

**Comment by ryb73** [comment]
Thanks for checking this out! Sorry about the delay.

> Ah. So I made a release using skip cleanup, but I think an additional reason why lib is not included is because it `./lib` in `.gitignore`, which npm respects unless it is overridden by `.npmignore`

I think the `files` attribute in package.json should override that. I can't find that stated in the docs but that's what I've done on some of my own projects.

> On that note, is it best practise to include pre-compiled js files in libraries?

Good question. I asked on the Discord once and only got one reply from someone else who said they publish `lib`. It'd be great if there were an official recommendation from the BuckleScript team.

Anyway, I'll describe my scenario and why it's not working for me without `lib` published: I have a CLI app that I want to be able to `npm install` and run immediately without compiling. The "binary" that's run is my compiled BS script at `lib/src/index.js`.

`bs-express` is a dependency of this app, which means my compiled `lib/src/index.js` at some point has a `require("bs-express/lib/js/src/...")` which fails if `lib/` isn't published.

I know I said I'd take a look, but it's likely I won't get a chance for at least a couple weeks. Don't worry about rushing this on my account though. :)

**Comment by ncthbrt** [comment]
`v.0.11.4` should now include the lib folder @ryb73.

**Comment by ryb73** [comment]
Thanks for publishing! I appreciate your help with this issue.

I can confirm that my app is closer to working, but still not there 😅 . My problem now is that my app (and some dependencies) were compiled with a different version of `bs-platform`, and the compiled output seems to be incompatible.

At this point I feel like I have no idea what the right solution is. I'm about to get on a plane to ReasonConf, so hopefully someone there can fill me in on how deployment of Reason apps is supposed to work 😄

**Comment by ncthbrt** [comment]
@ryb73  We could always update the version of bs-platform used in `bs-express`?

**Comment by ncthbrt** [comment]
I'm going to close this issue. Hopefully bs-express can work for your application now that we've bumped the version. Let me know if not.
