### ISSUE TITLE
Binding for server.on

### ISSUE THREAD

**Issue by strdr4605** [BuckleTypes/bs-express#64]
@Et7f3 suggested rewriting https://github.com/reasonml-community/bs-express/blob/master/example/Index.re#L483 in Reasonml.

He pointed to https://github.com/TomLingham/bs-node-http/blob/master/src/Http.re#L102-L105.

I am not fully understanding how to solve this issue and write bindings but I would like to find out how!

**Comment by ncthbrt** [comment]
Hi @strdr4605. That'd certainly be possible. I'd be happy to take a PR which would add bindings for `server.on` 

You'll note that line in question was a quick hack I added to enable me to test request counts when running integration tests, so I wouldn't worry necessarily about that exact function, but I can see how being able to add event listeners to the server would be useful.

**Comment by ncthbrt** [comment]
I still need to publish this change.
