### ISSUE TITLE
Should package-lock be ignored!?

### ISSUE THREAD

**Issue by strdr4605** [BuckleTypes/bs-express#66]
I read https://www.twilio.com/blog/lockfiles-nodejs a while ago. 
And as I understand package-lock is useless when publishing a package to npm (as bs-express is). To not have conflicts between development and production versions maybe is better to ignore package-lock.json?!

**Comment by ncthbrt** [comment]
That seems to make sense.

**Comment by ncthbrt** [comment]
Done

**Comment by strdr4605** [comment]
Also, you can add `.npmrc` file with `package-lock=false` which will prevent package-lock to be generated!
