### ISSUE TITLE
Fails to work with BuckleScript 5.2.0 onwards in production mode

### ISSUE THREAD

**Issue by ochrons** [BuckleTypes/bs-express#70]
Due to change in BS (https://bucklescript.github.io/blog/2019/09/23/release-5-20-0) local modules are no longer array but objects, which breaks compatibility when the bs-express library is used with `npm i --production` (for example under Google Cloud Functions)

**Comment by ncthbrt** [comment]
Oh dear. What changes are required to restore support?

**Comment by ochrons** [comment]
I believe just compiling with 5.2+ and republishing. It works locally just fine. This is of course not specific to bs-express but affects all libraries that expose JS built with older BS versions.

**Comment by ochrons** [comment]
To further clarify, this happens on `nodejs` where the platform fetches the compiled JS files from packages automatically (no build time bundling). These are compiled with an older version of Bucklescript, which produces JS that is not compatible with the latest version.

For example in 5.2:
```js
var $$Response = {
  StatusCode: Response_StatusCode,
  sendFile: Response_sendFile,
  sendString: Response_sendString,
```
and in 5.1
```js
var $$Response = [
  Response_000,
  Response_001,
  Response_002,
```

**Comment by ncthbrt** [comment]
Ah. I see. Will publish a new version tomorrow then. Thanks for letting me
know.

**Comment by ncthbrt** [comment]
@ochrons I've released a new version of bs-express. Would you mind verifying that it is working correctly for your use case? I've bumped the lib to v1 due to the bucklescript breaking changes

**Comment by ochrons** [comment]
Works fine with 1.0.0, thanks for the quick response!
