### ISSUE TITLE
Request headers?

### ISSUE THREAD

**Issue by adnelson** [BuckleTypes/bs-express#72]
Hi, I didn't see anything in the example file or `Express.re` for getting headers out of a request. I can write my own code to do it but I wanted to check if I'm missing something.

**Comment by ncthbrt** [comment]
@adnelson 
Under Request:
```ocaml
 /** [get return field] returns the specified HTTP request header
       field (case-insensitive match) */
  let get: (string, t) => option(string);
```

**Comment by adnelson** [comment]
Oh, ok, I was looking in the `.re` file as opposed to the `.rei` file. Thanks for the clarification! I kind of wish it were called `getHeader` or something as opposed to `get`, seeing as it would better correspond to `Response.setHeader`. Also I'm a little confused by the layout of the comments around these functions in `Express.re`:

```reason
  [@bs.send.pipe: t] [@bs.return null_undefined_to_opt]
  external get : string => option(string) = "";

  /*** [get return field] returns the specified HTTP request header
       field (case-insensitive match) */
  [@bs.get] external xhr : t => bool = "";
  /*** [xhr request] returns [true] if the request’s X-Requested-With
       header field is "XMLHttpRequest", indicating that the request was
       issued by a client library such as jQuery */
```

In any case, thanks again for the answer!

**Comment by ncthbrt** [comment]
That'd make more sense. Get is wrapping the underlying express api.

Feel free to send a PR to make the comments better.

I'm not actively contributing to this repository, but am actively triaging
issues and reviewing PRs.
