### ISSUE TITLE
Add external and @bs annotation in .rei file

### ISSUE THREAD

**Issue by tsnobip** [BuckleTypes/bs-express#76]
I've noticed that there is an interface file for the bindings which is not very common. I just briefly looked at the implementation and interface files and I couldn't see any functions or modules hidden by the interface files, maybe it could be removed altogether and the documentation transferred to the implementation file? 

If you prefer to keep the interface file, then it'd be nice to copy the external and @bs annotations to the interface file so the bindings don't generate extra js functions as advised in the docs (https://bucklescript.github.io/docs/en/intro-to-external#docsNav), would you have anything against that?

**Comment by ncthbrt** [comment]
Hi @tsnobip. I don't have any problem with that. Would you be willing to make a PR for it?

**Comment by tsnobip** [comment]
I  don't use bs-express these days, but once I'm back to it I'll work on a PR then :)

**Comment by LaMavia** [comment]
@ncthbrt I think this issue can be closed since external bs annotations where added in #85

**Comment by ncthbrt** [comment]
Great!
