### ISSUE TITLE
How can use middlewares like HelmetJS from the app.use?

### ISSUE THREAD

**Issue by matzero** [BuckleTypes/bs-express#77]
If you wanted to use any middleware like https://helmetjs.github.io/ where in plain js you can do: `app.use(helmet())`.
Assuming that I have binded the helmet() part to ReasonML already would you do `Routable.use(helmet())` to recreate the line `app.use(helmet())` in plain js?

**Comment by ncthbrt** [comment]
@matzero You'd want to go `App.use(app, helmet());` or `Router.use(router, helmet());`

**Comment by matzero** [comment]
Thanks!
